apiVersion: v1
kind: Secret
metadata:
  name: volume-azurefile-storage-secret
type: Opaque
data:
  azurestorageaccountname: cG5jb250YWluZXJkYXRh
  azurestorageaccountkey: YnlYR0FLUFNnZysxRzRSeEJMS0dURWFnUUNIWjhQTGJETUtKRVQ1bEU5YUJXbEZhcHlvZXFVZWhQSlNONlFXTGRJa1dmUEpnZy9OL1lrTDNXdUdGK1E9PQ==